config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :galleries
    collection do 
      get 'galleries'
    end
  end
  resources :users
  resources :password_resets
  resources :sliders
  resources :clients
  resources :contacts, only: [:new, :create]
  resources :testimonials, only: [:new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :signout
  get 'company/profile_1/:event_organizer', to: 'events#company', as: :company_event_organizer
  get 'company/profile_2/:corporate_gathering', to: 'events#company', as: :company_corporate_gathering
  get 'company/profile_3/:creative_concept', to: 'events#company', as: :company_creative_concept
  get 'company/profile_4/:audio_visual', to: 'events#company', as: :company_audio_visual
  get 'company/profile_5/:event_equipment', to: 'events#company', as: :company_event_equipment
  get 'company/profile_6/:advertising', to: 'events#company', as: :company_ads
  get 'company/profile_7/:design_graphic_design', to: 'events#company', as: :company_3d_design
  get 'galleries', to: 'events#all_gallery', as: :all_gallery
  get 'admin/dashboard', to: 'admins#dashboard', as: :dashboard
  get 'admin/events', to: 'events#all_event', as: :all_event
  get 'admin/sliders', to: 'sliders#all_slider', as: :all_slider
  get 'admin/testimonials', to: 'testimonials#all_testimonial', as: :all_testimonial
  get 'admin/users/', to: 'users#all_user', as: :all_user
  root 'events#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token
  before_save :email_downcase
  validates :username, presence: true, length: { maximum: 50 }
  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 9}, :on => :update, :unless => lambda{ |user| user.password.blank? }#, :on => :create, :unless => lambda{ |user| user.password.blank? }
  validates :password_confirmation, presence: true, allow_nil: true
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end 

  has_many :events

  def create_reset_digest
    self.reset_token = User.new_token
   update_attribute(:reset_digest, User.digest(reset_token))
   update_attribute(:reset_sent_at, Time.zone.now)
   # update_columns(reset_digest:  FILL_IN, reset_sent_at: FILL_IN)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if remember_digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  mount_uploader :profile, ProfileUploader
  
  private

  def email_downcase
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :signed_in_user
  before_action :find_user, only: [:edit, :update]

  layout "auth"

  def new
    @user = User.new
    render layout: "admin"
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    render layout: "admin"

  end

  def all_user
    @users = User.all.order('created_at desc')
    render layout: "admin"
  end

  def update
    if @user.update(user_params)
      redirect_to dashboard_url, success: "Accout have updated"
    else
      redirect_to edit_user_path(current_user), danger: "please check all fields"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to all_user_url
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :first_name, :profile, :status, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_url, notice: "Please sign in."
    end
  end

  def redirect_signed_in_user
    unless signed_in?
      redirect_to root_url, notice: "Please sign in."
    end
  end

  def redirect_signed_in_user_from_signin
    redirect_to user_url(current_user) if signed_in?
  end
end

app/views/users/_form.html.erb
<div class="login">
  <div class="frame">
    <h2 class="text-center title">RUANG IDE</h2>
    <div class="ckdj">
      <%= form_for(@user, url: signup_path) do |f| %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control", autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <div class="col-md-6" style="padding-left: 0px;">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="col-md-6" style="padding-right: 0px;">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>
      <div class="clear" style="clear: both;"></div>
      
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %> 
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.check_box :status %> <span>Make super user</span>
      </div>
      <%= f.submit "Sign Up", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/all_user.html.erb
<div class="contain">
  <div class="top_tit">
   <h2 class="title">All Users</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
      	<% unless !current_user.status? %>
        <li><%= link_to new_user_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <% end %>
        <li><%= link_to all_slider_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <div class="row dashgy">
      <% @users.each do |user| %>
      <% unless current_user.id == user.id %>
      <div class="col-xs-6 col-md-3">
        <a class="thumbnail whdtdhg">
        <% if !current_user.profile.present? %>
        	<%= image_tag "default/thumbr_as.jpg" %>
        <% else %>
          <%= image_tag user.profile_url(:thumbr) %>
        <% end %>
        </a>
        <div class="dagsjh" style="height: 236px;">
          <ul class="list-inline lsj" style="padding-top: 100px;">
          	<% unless !current_user.status? %>
            <li><%= link_to user, method: :delete, class: "destroy" do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %></li>
            <% end %>
          </ul>
        </div>
        <div class="caption">
          <h3><%= truncate(user.username, length: 20) %></h3>
        </div>
      </div>
      <% end %>
    <% end %>
    <div class="clear"></div>
    </div>
  </div>
</div>
<script>
  $('.respond').removeClass("aktif");      
  $('.admin__').addClass('aktif');
</script>

app/views/users/edit.html.erb
<div class="contain">
	<div class="top_tit">
		<h2 class="title">Update Account</h2>
	</div>
	<div class="btn_jh">
		<div class="idis">
			<ul class="list-inline hdgwt">
				<% unless !current_user.status? %>
				<li><%= link_to new_user_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
				<% end %>
				<li><%= link_to all_user_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
			</ul>
		</div>
	</div>
	<div class="cont_ii">
		<div class="login">
			<div class="frame">
				<h2 class="text-center title">RUANG IDE</h2>
				<div class="ckdj">
					<%= form_for(@user) do |f| %>
					<div class="form-group">
						<%= f.label :username %>
						<%= f.text_field :username, class: "form-control", autofocus: true %>
					</div>

					<div class="form-group">
						<%= f.label :email %>
						<%= f.email_field :email, class: "form-control" %>
					</div>
					<div class="form-group">
						<div class="col-md-6" style="padding-left: 0px;">
							<%= f.label :first_name %>
							<%= f.text_field :first_name, class: "form-control" %>
						</div>
						<div class="col-md-6" style="padding-right: 0px;">
							<%= f.label :last_name %>
							<%= f.text_field :last_name, class: "form-control" %>
						</div>
						<div class="clear" style="clear: both;"></div>
					</div>
					<div class="form-group">
						<%= f.label :profile, "Profile Picture" %>
						<%= f.file_field :profile %>
					</div>
					
					<br><br>
					<%= f.submit "Update", class: "btn btn-success" %>
					<% end %>
				</div>
			</div>
		</div>

	</div>
</div>
<script>
	$('.respond').removeClass("aktif");      
	$('.dashboard__').addClass('aktif');
</script>

app/views/users/new.html.erb
<div class="contain">
  <div class="top_tit">
   <h2 class="title">Add New User</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_user_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_user_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render 'users/form' %>
  </div>
</div>
<script>
  $('.respond').removeClass("aktif");      
  $('.admin__').addClass('aktif');
</script>