config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :galleries
    collection do 
      get 'galleries'
    end
  end
  resources :users
  resources :password_resets
  resources :sliders
  resources :clients
  resources :contacts, only: [:new, :create]
  resources :testimonials, only: [:new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :signout
  get 'company/profile_1/:event_organizer', to: 'events#company', as: :company_event_organizer
  get 'company/profile_2/:corporate_gathering', to: 'events#company', as: :company_corporate_gathering
  get 'company/profile_3/:creative_concept', to: 'events#company', as: :company_creative_concept
  get 'company/profile_4/:audio_visual', to: 'events#company', as: :company_audio_visual
  get 'company/profile_5/:event_equipment', to: 'events#company', as: :company_event_equipment
  get 'company/profile_6/:advertising', to: 'events#company', as: :company_ads
  get 'company/profile_7/:design_graphic_design', to: 'events#company', as: :company_3d_design
  get 'galleries', to: 'events#all_gallery', as: :all_gallery
  get 'admin/dashboard', to: 'admins#dashboard', as: :dashboard
  get 'admin/events', to: 'events#all_event', as: :all_event
  get 'admin/sliders', to: 'sliders#all_slider', as: :all_slider
  get 'admin/testimonials', to: 'testimonials#all_testimonial', as: :all_testimonial
  get 'admin/users/', to: 'users#all_user', as: :all_user
  root 'events#index'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :signed_in_user
  before_action :set_test, only: [:edit, :update, :destroy]
  layout "admin"
  def new
    @testimonial = Testimonial.new
  end


  def create
    @testimonial = Testimonial.new(params_test)
    if @testimonial.save
      redirect_to all_testimonial_path
    else 
      render 'new'
    end
  end

  def edit

  end

  def update
    if @testimonial.update(params_test)
      redirect_to all_testimonial_path
    else
      render 'edit'
    end
  end

  def all_testimonial
    @tests = Testimonial.all.order('created_at desc')
    render layout: "admin"
  end

  def destroy
    @testimonial.destroy
    redirect_to all_testimonial_url
  end

  private

  def params_test
    params.require(:testimonial).permit(:name, :content, :avatar, :occupation)
  end

  def set_test
    @testimonial = Testimonial.find(params[:id])
  end
end

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :occupation %>
    <%= f.text_area :occupation, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :avatar, "Avatar" %>
    <%= f.file_field :avatar %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/testimonials/all_testimonial.html.erb
<div class="contain">
  <div class="top_tit">
   <h2 class="title">All Testimonial</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_testimonial_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_testimonial_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <div class="testimonaial edbsg" style="width: 100%;">
      <div class="leyr titl">
        <p class="hsy">all the testimonial that have been added <span class="pull-right hgdr"><%= @tests.count %></span></p>
      </div>
      <div class="dhjwt">
        <ul class="cbdq">
          <% @tests.each_with_index do |test, index| %>
            <li class="ang <%= 'cvdg' if (index + 1)%2 == 0 %>">
              <ul class="list-inline najhs">
                <li class="name_" style="width: 250px !important;"><%= truncate(test.name, length: 19) %></li>
                <li class="user_ content_" style="width: 570px !important"><%= truncate(test.content, length: 100) %></li>
                <li class="created_at_"  style="width: 135px !important; border-right: 1px solid #e7ebf1 !important;"><%= test.created_at.strftime("%d %B %Y") %></li>
                <li class="actions_">
                  <ul class="list-inline ahster">
                    <li><%= link_to edit_testimonial_path(test) do %><i class="fa fa-pencil-square-o" aria-hidden="true"></i><% end %></li>
                    <li><%= link_to test, method: :delete do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %></li>
                  </ul>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<script>
  $('.respond').removeClass("aktif");      
  $('.testimonial__').addClass('aktif');
</script>

app/views/testimonials/edit.html.erb
<div class="contain">
  <div class="top_tit">
   <h2 class="title">Edit Testimonials</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
         <li><%= link_to new_testimonial_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_testimonial_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render "testimonials/form" %>
  </div>
</div>
<script>
  $('.respond').removeClass("aktif");      
  $('.testimonial__').addClass('aktif');
</script>

app/views/testimonials/new.html.erb
<div class="contain">
  <div class="top_tit">
   <h2 class="title">Add New Testimonials</h2>
  </div>
  <div class="btn_jh">
    <div class="idis">
      <ul class="list-inline hdgwt">
        <li><%= link_to new_testimonial_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></li>
        <li><%= link_to all_testimonial_url do %><i class="fa fa-folder-open" aria-hidden="true"></i><% end %></li>
      </ul>
    </div>
  </div>
  <div class="cont_ii">
    <%= render "testimonials/form" %>
  </div>
</div>
<script>
  $('.respond').removeClass("aktif");      
  $('.testimonial__').addClass('aktif');
</script>