config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :galleries
    collection do 
      get 'galleries'
    end
  end
  resources :users
  resources :password_resets
  resources :sliders
  resources :clients
  resources :contacts, only: [:new, :create]
  resources :testimonials, only: [:new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :signout
  get 'company/profile_1/:event_organizer', to: 'events#company', as: :company_event_organizer
  get 'company/profile_2/:corporate_gathering', to: 'events#company', as: :company_corporate_gathering
  get 'company/profile_3/:creative_concept', to: 'events#company', as: :company_creative_concept
  get 'company/profile_4/:audio_visual', to: 'events#company', as: :company_audio_visual
  get 'company/profile_5/:event_equipment', to: 'events#company', as: :company_event_equipment
  get 'company/profile_6/:advertising', to: 'events#company', as: :company_ads
  get 'company/profile_7/:design_graphic_design', to: 'events#company', as: :company_3d_design
  get 'galleries', to: 'events#all_gallery', as: :all_gallery
  get 'admin/dashboard', to: 'admins#dashboard', as: :dashboard
  get 'admin/events', to: 'events#all_event', as: :all_event
  get 'admin/sliders', to: 'sliders#all_slider', as: :all_slider
  get 'admin/testimonials', to: 'testimonials#all_testimonial', as: :all_testimonial
  get 'admin/users/', to: 'users#all_user', as: :all_user
  root 'events#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html id="top_nav">
  <head>
    <title>Ruang Ide Event Organizer</title>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Bilbo+Swash+Caps|Great+Vibes|Montez|Over+the+Rainbow|Rancho|Roboto+Slab:300,400,700|Roboto:300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>
  <body>
    <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>" style="margin-bottom: 0px; text-align: center;position: absolute;z-index: 999;width: 100%;">
      <%= msg %> <span id= "close_alt" class="pull-right fa fa-close" style="cursor: pointer;"></span>
    </div>
    <% end %>
    <div class="navbar navbar-default top_nav">
      <div class="container-fluid nejg">
        <div class="navbar-header">
          <%= link_to "RUANG IDE", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right ghkjh">
          <li class="dropdown">
            <% if !current_user.profile.present? %>
              <%= image_tag "default/default_profile.png" %>
            <% else %>
              <%= image_tag current_user.profile_url(:thumb) %>
            <% end %>
            <a class="jdfu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= current_user.username %></a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "SETTING", edit_user_path(current_user), class: "sdh" %></li> 
              <li><%= link_to "LOGOUT", signout_path, method: "delete", class: "sdh" %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <div class="navbar navbar-default left_nav">
      <div class="ahg">
        <p class="dash_brd respond aktif"><i class="fa fa-tachometer" aria-hidden="true"></i><%= link_to "Dashboard", dashboard_path %></p>
        <p class="event__ respond"><i class="fa fa-suitcase" aria-hidden="true"></i><%= link_to "Event", all_event_url %></p>
        <p class="slider__ respond"><i class="fa fa-retweet" aria-hidden="true"></i><%= link_to "Slider", all_slider_url %></p>
        <p class="testimonial__ respond"><i class="fa fa-users" aria-hidden="true"></i><%= link_to "Testimonial", all_testimonial_url %></p>
        <p class="admin__ respond"><i class="fa fa-users" aria-hidden="true"></i><%= link_to "Users", all_user_url %></p>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html id="top_nav">
  <head>
    <title>Ruang Ide Event Organizer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Bilbo+Swash+Caps|Great+Vibes|Montez|Over+the+Rainbow|Rancho|Roboto+Slab:300,400,700|Roboto:300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>
  <body>
  <nav id="mainNav_1" class="navbar navbar-default navbar-custom navbar-custom_1 navbar-fixed-top">
      <div class="container custome_container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse custome-collapse" id="navbar-collapse-1" style="text-align: center">
          <ul class="nav navbar-nav navbar-left">
            <li><a class="page-scroll" href="#company_profile">Company Profile</a></li>
            <li><a class="page-scroll" href="#eventSlider">Event</a></li>
            <li><a class="page-scroll" href="#gallery">Gallery</a></li>
          </ul>
          <a class="navbar-brand page-scroll" href="#top_nav">
            RI<br>
            <span>RUANG IDE</span>
          </a>
          <ul class="nav navbar-nav navbar-right">
            <li class="port"><a href="#service" class="page-scroll">Portfolio</a>
              <ul class="drp_down">
                <li><a href="#service" class="page-scroll">Service</a></li>
              </ul>
            </li>
            <li><a href="#contact" class="page-scroll">Contact</a></li>
            <li><a href="#testimonial" class="page-scroll">Testimonial</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container custome_container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse custome-collapse" id="navbar-collapse-1" style="text-align: center">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="#company_profile" class="page-scroll">Company Profile</a></li>
            <li><a href="#eventSlider" class="page-scroll">Event</a></li>
            <li><a href="#gallery" class="page-scroll">Gallery</a></li>
          </ul>
          <a class="navbar-brand scroll-page" href="#top_nav">
            RI<br>
            <span>RUANG IDE</span>
          </a>
          <ul class="nav navbar-nav navbar-right">
            <li class="port"><a href="#service" class="page-scroll">Portfolio</a>
              <ul class="drp_down_">
                <li><a href="#service" class="page-scroll">Service</a></li>
              </ul>
            </li>
            <li><a href="#contact" class="page-scroll">Contact</a></li>
            <li><a href="#testimonial" class="page-scroll">Testimonial</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="containers">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html id="top_nav">
<head>
	<title>Ruang Ide Event Organizer</title>
	<%= stylesheet_link_tag    'auth', media: 'all', 'data-turbolinks-track' => false %>
	<%= javascript_include_tag 'auth', 'data-turbolinks-track' => false %>
	<%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/css?family=Bilbo+Swash+Caps|Great+Vibes|Montez|Over+the+Rainbow|Rancho|Roboto+Slab:300,400,700|Roboto:300,400,500,700,900" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
<body>
	<% flash.each do |name, msg| %>
		<div class="alert alert-<%= name %>" style="margin-bottom: 0px; text-align: center;position: absolute;z-index: 999;width: 100%;">
			<%= msg %> <span id= "close_alt" class="pull-right fa fa-close" style="cursor: pointer;"></span>
		</div>
	<% end %>
	<div class="containers">
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/todo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruang Ide Event Organizer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'todo', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Bilbo+Swash+Caps|Great+Vibes|Montez|Over+the+Rainbow|Rancho|Roboto+Slab:300,400,700|Roboto:300,400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>
  <body>
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>" style="margin-bottom: 0px; text-align: center;position: absolute;z-index: 999;width: 100%;">
      <%= msg %> <span id= "close_alt" class="pull-right fa fa-close" style="cursor: pointer;"></span>
    </div>
  <% end %>
  <nav id="mainNav_1" class="navbar navbar-default navbar-custom honestly navbar-custom_1 navbar-fixed-top">
      <div class="container custome_container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse custome-collapse" id="navbar-collapse-1" style="text-align: center">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="#" class="comapny">Company Profile</a></li>
            <li><a href="#" class="ev_ent">Event</a></li>
            <li><a href="#" class="gal_er">Gallery</a></li>
          </ul>
          <a class="navbar-brand" href="#">
            RI<br>
            <span>RUANG IDE</span>
          </a>
          <ul class="nav navbar-nav navbar-right">
            <li class="port"><a href="#">Portfolio</a>
              <ul class="drp_down">
                <li><a href="#">Service</a></li>
              </ul>
            </li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Testimonial</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav> 
    <div class="containers">
      <%= yield %>
    </div>
  </body>
</html>